project_id = "ustogether"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
site_url = "http://localhost:8081"
additional_redirect_urls = ["ustogether://**", "http://localhost:8081/**"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
